import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StarsCanvas from '@/components/main/StarBackground'
import "./globals.css";
import Navbar from "@/components/main/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Personal Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} bg-[#030014] overflow-y-hidden overflow-x-hidden py-40`}
        >
                <StarsCanvas />
                <Navbar />
                {children}
            </body>
        </html>
    );
}
